parameters:
    hari.post.entity: 'HariBundle\Entity\Post'
    google_client: Google_Client
    
services:
    
    hari.abstract.class:
        class: HariBundle\EntityHandler\Handler
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@security.authorization_checker"
        
             
    hari.post_handler:
        class: HariBundle\EntityHandler\PostHandler
        parent: hari.abstract.class
        calls:
            - [ startService, [ '%hari.post.entity%' ] ]
       
        
    hari.post.doctrine.listener:
        class: HariBundle\EventListener\PostEventListener
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
#    hari.example:
#        class: HariBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
